### ISSUE TITLE
Don't list every single site

### ISSUE THREAD

**Issue by WebTrooper** [thenbrent/multisite-user-management#18]
Thank you for this very useful plugin but it does have one major drawback in that it lists every single site in the network admin settings. Many multisite networks consist of hundreds or even thousands of sites. It would be better to have a search form, rather than loading that huge list.

**Comment by thenbrent** [comment]
@WebTrooper thanks for the report I'm aware of the issue as one other use had it a couple of years ago. I don't have any plans to rewrite it to handle it better at the moment (probably by paginating the sites in batches of 15-20), but if you want to work on it or hire a developer to fix it up I can provide some guidance on how I would implement it.

**Comment by WebTrooper** [comment]
Thanks for the quick reply. For my purposes I can just set it up once then hide the list. It's still a very useful plugin.
