### ISSUE TITLE
make deploy.sh cross platform

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [thenbrent/multisite-user-management#19]
right now deploy.sh assumes you're on Ubuntu (or a linux system with `dpkg-query` installed) with this line:

`if [ $(dpkg-query -W -f='${Status}' subversion 2>/dev/null | grep -c "ok installed") != "1" ]`

After confirming [subversion always has a 3 digit version](https://subversion.apache.org/docs/release-notes/release-history.html) (well, for the last 11 years), I believe this line would work on all platforms. It's what I use on my mac:

`if [ $(svn --version --quiet|egrep -c '^[0-9]+\.[0-9]+\.[0-9]+$' 2>/dev/null) != "1" ]`

**Comment by thenbrent** [comment]
@Ths2-9Y-LqJt6 thanks for the report. The `.deploy.sh` script is only a small part of this repo and it's been extended and enhanced much more by others beyond what I have here.

You might have better luck using one of these:

* https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy
* https://github.com/benbalter/Github-to-WordPress-Plugin-Directory-Deployment-Script

**Comment by Ths2-9Y-LqJt6** [comment]
@thenbrent  - cool cool, makes sense.  Thanks for the update!
