### ISSUE TITLE
Deploy script doesn't update

### ISSUE THREAD

**Issue by martinburchell** [thenbrent/multisite-user-management#20]
We've been using a modified version of your deploy script for our WordPress plugins. Thanks!

We noticed a problem when running the script. Around about line 68/69 there are these lines:
```
echo "Clearing svn repo so we can overwrite it"
svn rm $SVNPATH/trunk/*
```
We found we had to change the second line to:
```
rm -r $SVNPATH/trunk/*
```
otherwise the files in trunk in the subversion repository would just be deleted and not replaced with the updates from git

**Comment by thenbrent** [comment]
Thanks for the report. The `.deploy.sh` script is only a small part of this repo and it's been extended and enhanced much more by others beyond what I have here, so you might like to try one of these:

https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy
https://github.com/benbalter/Github-to-WordPress-Plugin-Directory-Deployment-Script

Then you can include your own revisions in that script.
