### ISSUE TITLE
deploy.sh script for boilerplate code 

### ISSUE THREAD

**Issue by aurovrata** [thenbrent/multisite-user-management#24]
The `deploy.sh` script fails to get the version number in the plugin php file created using boilerplate code because the version tag is listed as,

>`*` Version:` ` ` ` ` `1.0.0

the comment section is implemented with an '*' at the beginning of each line, and several spaces are inserted between the Version tag and the number.  Hence grep and awk commands are unable to process it.  This is easily fixed with the following modification to line 36,

`
NEWVERSION2=`grep "Version:" $GITPATH/$MAINFILE | awk -F'[[:space:]]+ ' '{print $NF}'`
`

I hope this is helpful to others who want to manage their wordpress plugins in Github.

**Comment by thenbrent** [comment]
Hi @aurovrata, thanks for sharing that info to help others.

This repo isn't really about `deploy.sh`, that's just here for deployment the Multisite User Management plugin. The Issues for this repo are for that plugin too, so I'll close this one as it's unrelated to that.

FWIW there are a number of standalone deployment scripts now which Google will direct you to (I don't know the best one or two off the top of my head sorry). Those have a lot more features and probably better `readme.txt` parsing than `deploy.sh`. 😄

**Comment by aurovrata** [comment]
HI @thenbrent 
sure I understand, I have been looking around various places to find out how devs manage WP plugins with GitHub.  There are quite a varied number of ways, some complex, some that bypass the WP svn repo altogether, but I find your approach much more simple.  I came across it in a stackoverflow thread.
I will try and Google some more on this method as you suggest.
thank you.
