### ISSUE TITLE
Pick a License, Any License

### ISSUE THREAD

**Issue by jhabdas** [thenbrent/multisite-user-management#25]
https://blog.codinghorror.com/pick-a-license-any-license/

**Comment by thenbrent** [comment]
GPLv2

**Comment by ghost** [comment]
Thanks @thenbrent. I believe GPL-2.0 automatically uses GPL-3.0, which you could use if you wanted to provide the most transparent licensing terms to users. Cheers and thanks for licensing your software for use by others.

**Comment by ghost** [comment]
> I believe GPL-2.0 automatically uses GPL-3.0, which you could use if you wanted to provide the most transparent licensing terms to users. Cheers and thanks for licensing your software for use by others.

Update to the above. For GPL2 to auto-upgrade it must be applied. See https://choosealicense.com/licenses/gpl-2.0/

**Comment by ghost** [comment]
FYI https://github.com/xwp/wp-dev-lib/issues/240#issuecomment-303029913

**Comment by thenbrent** [comment]
> it must be applied

Yes, I'm aware. I deliberately chose v2. 🙂
